title = "Leigh Oliver"
baseURL = "https://leigholiver.com"
languageCode = "en-gb"
theme = "bulb"

[Params]
sidebar_image = "/images/profile.jpeg"
sidebar_text = "Cloud/DevOps/Software engineer"
sidebar_image_credit = "Photo: Bethany Lock"
google_analytics = "UA-180824262-1"
# footer_text = "A erat nam at lectus urna duis. Sed velit dignissim sodales ut eu sem."

[[Params.socials]]
    icon = "twitter-square"
    url = "https://twitter.com/leigholiver_"
[[Params.socials]]
    icon = "linkedin"
    url = "https://www.linkedin.com/in/leigh-oliver-32ab63187/"
[[Params.socials]]
    icon = "github-square"
    url = "https://github.com/leigholiver"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
