title = "Leigh Oliver"
baseURL = "https://leigholiver.com"
languageCode = "en-gb"
theme = "bulb"

[Params]
sidebar_image = "/images/profile.webp"
# sidebar_text = "Platform Engineer"
sidebar_image_credit = "Photo: Bethany Lock"
google_analytics = "UA-180824262-1"

[[Params.socials]]
    icon = "twitter-square"
    url = "https://twitter.com/leigholiver_"
[[Params.socials]]
    icon = "linkedin"
    url = "https://www.linkedin.com/in/leigh-oliver-32ab63187/"
[[Params.socials]]
    icon = "github-square"
    url = "https://github.com/leigholiver"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[Params.theme.light]
text = ""
bg = ""
bg_alt = ""
interactive = ""
focus = ""

[Params.theme.dark]
text = ""
bg = ""
bg_alt = ""
interactive = ""
focus = ""
