title = "Leigh Oliver"
baseURL = "https://leigholiver.com"
languageCode = "en-gb"
theme = "bulb"

[Params]
sidebar_image = "/images/profile.png"
sidebar_text = "DevOps Engineer and Software Developer"
google_analytics = "UA-180824262-1"
# footer_text = "A erat nam at lectus urna duis. Sed velit dignissim sodales ut eu sem."

[[Params.socials]]
    icon = "github-square"
    url = "https://github.com/leigholiver"
[[Params.socials]]
    icon = "twitter-square"
    url = "https://twitter.com/leigholiver_"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
