title: Leigh Oliver
description: Software developer and DevOps engineer

baseurl: "/"
url: "https://leigholiver.com"
google_analytics: UA-180824262-1
email: leigh@leigholiver.com
github_username: leigholiver
twitter_username: _leigholiver

markdown: kramdown
theme: minima
plugins:
  - jekyll-timeago
